list=[]
txt="""Brave
Bright
Calm
Careful
Cheerful
Clever
Cold
Colorful
Curious
Dark
Deep
Delicate
Dizzy
Dull
Dusty
Early
Elegant
Energetic
Fancy
Fast
Fearless
Fiery
Flat
Friendly
Gentle
Giant
Gleaming
Graceful
Happy
Harsh
Healthy
Heavy
Honest
Hot
Humble
Hungry
Icy
Intelligent
Invisible
Jolly
Juicy
Kind
Large
Lazy
Light
Lonely
Loud
Majestic
Mellow
Messy
Modern
Mysterious
Nervous
Nice
Noisy
Odd
Old
Peaceful
Pink
Pleasant
Polite
Poor
Powerful
Proud
Pure
Quick
Quiet
Rare
Red
Rich
Rough
Round
Sad
Shiny
Shy
Simple
Sleepy
Slow
Small
Smooth
Soft
Strong
Sweet
Tall
Thin
Tiny
Tough
Ugly
Unusual
Warm
Weak
Wet
Wide
Wild
Wise
Wonderful
Yellow
Young
Zany
Zealous
Able
Abundant
Accurate
Amazing
Angry
Ancient
Anxious
Average
Awkward
Bad
Beautiful
Bitter
Bitter
Blind
Boring
Broken
Busy
Capable
Careless
Cautious
Chilly
Clean
Clear
Cloudy
Clumsy
Cool
Crazy
Creepy
Crude
Cruel
Dangerous
Dead
Delicious
Depressed
Determined
Dirty
Dry
Eager
Easy
Educated
Effective
Efficient
Emotional
Empty
Envious
Evil
Excited
Expensive
Expert
Fabulous
Fair
Famous
Fascinating
Fat
Fierce
Fluffy
Fragile
Frightened
Frustrated
Funny
Gentle
Giant
Glorious
Good
Grateful
Green
Grumpy
Handsome
Happy
Hard
Harmful
Harsh
Hasty
Healthy
Heavy
Helpful
Helpless
Horrible
Hot
Huge
Humble
Hungry
Ignorant
Ill
Important
Impossible
Incredible
Insane
Inspiring
Interesting
Invisible
Irritating
Itchy
Jittery
Joyful
Juicy
Kind
Lazy
Light
Lively
Long
Lovely
Lucky
Lush
Mad
Mellow
Miserable
Modern
Muddy
Mysterious
Narrow
Nervous
Nice
Noisy
Obnoxious
Odd
Old
Open
Orange
Outrageous
Pale
Perfect
Plain
Playful
Polished
Poor
Powerful
Precious
Pretty
Proud
Puzzling
Quick
Quiet
Rainy
Rare
Raw
Ready
Real
Red
Relaxed
Rich
Rigid
Rough
Round
Royal
Rude
Sad
Safe
Salty
Scared
Scary
Secret
Shady
Shallow
Sharp
Shiny
Short
Shy
Silly
Simple
Skinny
Slow
Small
Smelly
Smooth
Soft
Solid
Sour
Sparkling
Special
Spicy
Spooky
Stable
Steady
Strange
Strong
Stubborn
Stupid
Successful
Sweet
Swift
Tasty
Tall
Terrible
Thankful
Thick
Thin
Thirsty
Tiny
Tired
Tough
Tricky
Ugly
Uncertain
Unique
Unlucky
Unusual
Useful
Useless
Vast
Violent
Warm
Weak
Wealthy
Wet
Wicked
Wide
Wild
Wise
Wonderful
Worn
Worrying
Wrinkled
Wrong
Yellow
Young
Zany
Zealous
Brave
Bold
Boring
Bright
Broad
Carefree
Caring
Cautious
Cheeky
Cheerful
Clever
Cold
Comfortable
Confident
Content
Cool
Courageous
Curious
Cunning
Dark
Deadly
Decisive
Delicate
Delicious
Dependable
Determined
Dirty
Distant
Dizzy
Double
Drab
Dramatic
Dreamy
Dry
Dull
Dusty
Early
Eccentric
Effective
Elegant
Elusive
Empty
Energetic
Enormous
Enthusiastic
Exciting
Exhausted
Exquisite
Fair
Faithful
Famous
Fantastic
Fearful
Fearless
Fierce
Fine
Flaky
Flat
Flexible
Foolish
Fragile
Friendly
Frightened
Funny
Fuzzy
Gentle
Giant
Gigantic
Gleaming
Gloomy
Glorious
Graceful
Grateful
Great
Green
Groovy
Grumpy
Hairy
Handsome
Harsh
Hasty
Healthy
Heavy
Helpful
Helpless
High
Hilarious
Hollow
Honest
Hot
Humble
Hungry
Hypnotic
Icy
Ignorant
Ill
Imaginative
Impatient
Important
Impossible
Incompetent
Independent
Indifferent
Industrious
Inexperienced
Innocent
Insane
Inspiring
Intelligent
Intense
Interesting
Invincible
Invisible
Irritable
Itchy
Joyful
Juicy"""

letter=""
for nothing in range(1):
    for word in txt:
        if word=="""
""":
            list.append(letter)
            letter=""
            continue
        letter+=word

print(list)

print(len(['Apple', 'Balloon', 'Camera', 'Dog', 'Elephant', 'Flower', 'Guitar', 'House', 'Island', 'Jacket', 'Kangaroo', 'Lemon', 'Mountain', 'Notebook', 'Ocean', 'Pencil', 'Queen', 'River', 'Sun', 'Tree', 'Umbrella', 'Village', 'Window', 'Xylophone', 'Yacht', 'Zebra', 'Book', 'Cloud', 'Door', 'Engine', 'Forest', 'Garden', 'Hat', 'Ice', 'Jewel', 'Kite', 'Light', 'Mirror', 'Nest', 'Owl', 'Penguin', 'Quilt', 'Rock', 'Snake', 'Table', 'Unicorn', 'Violin', 'Wolf', 'X-ray', 'Yarn', 'Zipper', 'Airplane', 'Bicycle', 'Clock', 'Desert', 'Egg', 'Fan', 'Glass', 'Hammer', 'Insect', 'Jet', 'Key', 'Lake', 'Monkey', 'Necklace', 'Octopus', 'Paint', 'Quilt', 'Ring', 'Star', 'Turtle', 'Vase', 'Water', 'Xenon', 'Yellow', 'Zebra', 'Anchor', 'Bridge', 'Chair', 'Drum', 'Eagle', 'Fish', 'Globe', 'Helmet', 'Ink', 'Jug', 'Kite', 'Ladder', 'Moon', 'Night', 'Oak', 'Path', 'Quilt', 'Rabbit', 'Ship', 'Train', 'Vase', 'Whale', 'X-ray', 'Yogurt', 'Ant', 'Bowl', 'Couch', 'Desk', 'Envelope', 'Fence', 'Grapes', 'Highway', 'Island', 'Jar', 'King', 'Lamp', 'Mango', 'Notebook', 'Ostrich', 'Plane', 'Quilt', 'Rose', 'Spoon', 'Turtle', 'Vase', 'Waterfall', 'Xylophone', 'Yacht', 'Zebra', 'Battery', 'Clock', 'Deer', 'Envelope', 'Fork', 'Grass', 'Helicopter', 'Iceberg', 'Joker', 'Ladder', 'Magnet', 'Nest', 'Orange', 'Pig', 'Quilt', 'Rabbit', 'Sunflower', 'Train', 'Unicorn', 'Vase', 'Watermelon', 'Yak', 'Zucchini', 'Atom', 'Box', 'Chair', 'Desk', 'Elephant', 'Fish', 'Gate', 'Hat', 'Ice', 'Juice', 'Kite', 'Light', 'Mask', 'Night', 'Owl', 'Pencil', 'Quilt', 'River', 'Snake', 'Tree', 'Umbrella', 'Vase', 'Waterfall', 'X-ray', 'Yarn', 'Zebra', 'Ambulance', 'Bridge', 'Calculator', 'Drum', 'Eagle', 'Fire', 'Globe', 'Hat', 'Iceberg', 'Jellyfish', 'Kite', 'Lamp', 'Mouse', 'Net', 'Ostrich', 'Pineapple', 'Quilt', 'Robot', 'Shark', 'Table', 'Umbrella', 'Van', 'Wolf', 'Xenon', 'Yarn', 'Zebra', 'Apple', 'Button', 'Card', 'Dog', 'Elephant', 'Frog', 'Guitar', 'House', 'Island', 'Jacket', 'Kangaroo', 'Lemon', 'Mountain', 'Notebook', 'Ocean', 'Pencil', 'Queen', 'River', 'Sun', 'Tree', 'Umbrella', 'Village', 'Window', 'Xylophone', 'Yacht', 'Zebra', 'Box', 'Clock', 'Deer', 'Elephant', 'Frog', 'Gate', 'Hat', 'Iceberg', 'Jackal', 'Kite', 'Ladder', 'Moon', 'Night', 'Orange', 'Pillow', 'Quilt', 'Radio', 'Sunflower', 'Turtle', 'Umbrella', 'Violin', 'Wolf', 'X-ray', 'Yak', 'Zebra', 'Ball', 'Car', 'Duck', 'Engine', 'Frog', 'Gate', 'Hat', 'Ice', 'Jar', 'King', 'Lamp', 'Moon', 'Nest', 'Octopus', 'Pig', 'Quilt', 'Ring', 'Sun', 'Train', 'Umbrella', 'Vase', 'Waterfall', 'Xenon', 'Yacht', 'Zebra', 'Anchor', 'Bag', 'Chair', 'Dog', 'Egg', 'Fire', 'Globe', 'Helicopter', 'Iceberg', 'Jet', 'Key', 'Ladder', 'Mouse', 'Net', 'Ostrich', 'Paint', 'Quilt', 'Rose', 'Star', 'Turtle', 'Vase', 'Water', 'Xenon', 'Yarn', 'Zebra', 'Arrow', 'Ball', 'Clock', 'Door', 'Elephant', 'Fire', 'Globe', 'Helicopter', 'Ink', 'Jug', 'Kite', 'Lamp', 'Moon', 'Night', 'Owl', 'Plane', 'Quilt', 'Ring', 'Star', 'Tree', 'Umbrella', 'Vase', 'Whale', 'Xenon', 'Yarn', 'Zebra', 'Apple', 'Bag', 'Cat', 'Dog', 'Elephant', 'Frog', 'Glass', 'Helicopter', 'Ice', 'Jack', 'Kite', 'Lamp', 'Moon', 'Night', 'Orange', 'Pillow', 'Quilt', 'Rock', 'Sunflower', 'Tree', 'Umbrella', 'Vase', 'Waterfall', 'Xenon', 'Yak', 'Zebra', 'Airplane', 'Bridge', 'Car', 'Dog', 'Egg', 'Fire', 'Globe', 'Helicopter', 'Ink', 'Jug', 'Kite', 'Lamp', 'Mouse', 'Nest', 'Octopus', 'Pig', 'Quilt', 'Radio', 'Star', 'Turtle', 'Umbrella', 'Violin', 'Wolf', 'Xenon', 'Yarn', 'Zebra', 'Bag', 'Cat', 'Door', 'Elephant', 'Frog', 'Gate', 'Hat', 'Ice', 'Jar', 'Kite', 'Lamp', 'Mask', 'Nest', 'Orange', 'Pineapple', 'Quilt', 'Rose', 'Star', 'Tree', 'Umbrella', 'Violin', 'Waterfall', 'Xenon', 'Yarn', 'Zebra', 'Airplane', 'Box', 'Car', 'Duck', 'Egg', 'Fish', 'Globe', 'Hat', 'Iceberg', 'Jackal', 'Key', 'Ladder', 'Moon', 'Night', 'Ostrich', 'Pillow', 'Quilt', 'Rose', 'Sun', 'Train', 'Unicorn', 'Vase', 'Water', 'Xenon', 'Yak', 'Zebra', 'Book', 'Cloud', 'Deer', 'Elephant', 'Fish', 'Gate', 'Hat', 'Iceberg', 'Jug', 'Kite', 'Lamp', 'Moon', 'Night', 'Owl', 'Pig', 'Quilt', 'Ring', 'Sun', 'Turtle', 'Umbrella', 'Vase', 'Waterfall', 'Xenon', 'Yarn', 'Zebra', 'Anchor', 'Bag', 'Chair', 'Dog', 'Egg', 'Fire', 'Globe', 'Helicopter', 'Ink', 'Jet', 'Key', 'Ladder', 'Moon', 'Nest', 'Octopus', 'Pig', 'Quilt', 'Rock', 'Sun', 'Turtle', 'Umbrella', 'Vase', 'Waterfall', 'Xenon', 'Yarn', 'Zebra', 'Apple', 'Bridge', 'Car', 'Dog', 'Elephant', 'Fire', 'Globe', 'Helicopter', 'Ice', 'Jug', 'Kite', 'Lamp', 'Mask', 'Nest', 'Owl', 'Pineapple', 'Quilt', 'Rose']))